version: "3"
services:
  simpleapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80"
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  
    ports:
      - "8080:80"
